In [7]:
from sonar.inference_pipelines.text import TextToEmbeddingModelPipeline, EmbeddingToTextModelPipeline

In [3]:
t2vec_model = TextToEmbeddingModelPipeline(encoder="text_sonar_basic_encoder",
                                           tokenizer="text_sonar_basic_encoder")


In [43]:
sentences = ['Patient has heart failure', 'Patient has a heart attack']
embeddings = t2vec_model.predict(sentences, source_lang="eng_Latn")
print(embeddings.shape)
# torch.Size([2, 1024])

torch.Size([2, 1024])


In [8]:
embeddings[1:]

tensor([[-0.0003, -0.0071,  0.0076,  ...,  0.0055,  0.0022, -0.0083]])

In [10]:
v2text_model = EmbeddingToTextModelPipeline(decoder="text_sonar_basic_decoder",
                                           tokenizer="text_sonar_basic_decoder")

In [ ]:
v2text_model.predict(embeddings[1:], target_lang="eng_Latn")

['I can embed the sentences into vector space.']

In [56]:
import torch
import numpy as np


tensor([[-0.0090,  0.0135,  0.0013,  ...,  0.0115,  0.0024, -0.0022],
        [ 0.0223,  0.0257,  0.0158,  ...,  0.0125, -0.0075, -0.0101]])

In [66]:
embeddings

tensor([[ 0.0252,  0.0007,  0.0239,  ...,  0.0376,  0.0625, -0.0064],
        [ 0.0797,  0.0241, -0.0499,  ...,  0.0305, -0.0382,  0.0090]])

In [75]:
sentences = ["""History of Present Illness:
Ms. ___ is an ___ year old female who was admitted to ___ 
in ___ after a syncopal fall while shopping. She sustained 
T3 & T6 vertebral fractures. She underwent an extensive workup 
during her admission, and brain imaging revealed an incidental 
2.4 x 1.5 cm left internal carotid aneurysm arising at the 
bifurcation of the posterior communicating artery. She follow-ed 
up with Dr. ___ in outpatient clinic, at which time it was 
determined that she will undergo elective pipeline embolization 
of aneurysm at left internal carotid/left posterior 
communicating artery bifurcation."""]
embeddings = t2vec_model.predict(sentences, source_lang="eng_Latn")
print(embeddings.shape)
# torch.Size([2, 1024])


torch.Size([1, 1024])


In [76]:
embeddings

tensor([[ 0.0161, -0.0092,  0.0024,  ..., -0.0074, -0.0075, -0.0166]])

In [77]:
v2text_model.predict(embeddings, target_lang="eng_Latn")

["History of the disease: Ms. _______ is a 2-year-old girl who was admitted to the hospital during an accidental drowning after joining and joining _______. She underwent T3 and T6 fractures during her admission, and during her admission she underwent extensive brain imaging, which revealed a 2.4 x 1.5 cm lateral left ventricular aneurysm of the left ventricular aneurysm that occurred during admission. She was followed by surgery at the doctor's clinic. She was advised that she would undergo an internal/external ventricular aneurysm of the left ventricular aneurysm during admission."]

In [70]:
embeddings = embeddings + torch.Tensor(np.random.normal(0, 0.01, embeddings.shape))
v2text_model.predict(embeddings, target_lang="eng_Latn")

['How can a sentence be long a sentence can be a sentence can be a sentence can be a sentence can be a sentence can be a sentence can be a sentence can be a sentence can be a sentence']